lint fixes

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -19,34 +19,38 @@ steps:
   entrypoint: 'sh'  
   args: 
   - '-c'
-  - | 
-      echo "***********************"
-      echo "$BRANCH_NAME"
-      echo "***********************"
+  - |
+      if [ -f "tfbackend/${BRANCH_NAME}.tfbackend"] && -f "tfvars/${BRANCH_NAME}.tfvars"]
+        echo "***********************"
+        echo "${BRANCH_NAME}"
+        echo "***********************"
+      else
+        if [ ! -f "tfbackend/${BRANCH_NAME}.tfbackend"]
+          echo "Missing file 'tfbackend/${BRANCH_NAME}.tfbackend'
+        fi
+        if [ ! -f "tfvars/${BRANCH_NAME}.tfvars"]
+          echo "Missing file 'tfvars/${BRANCH_NAME}.tfvars'
+        fi
+        exit 1
 
+# [START tf-init]
 - id: 'tf init'
   name: 'hashicorp/terraform:1.0.0'
   entrypoint: 'sh'
-  args: 
+  args:
   - '-c'
   - |
-      if [ -d "environments/$BRANCH_NAME/" ]; then
-        cd environments/$BRANCH_NAME
-        terraform init
-      else
-        for dir in environments/*/
-        do 
-          cd ${dir}   
-          env=${dir%*/}
-          env=${env#*/}
-          echo ""
-          echo "*************** TERRAFORM INIT ******************"
-          echo "******* At environment: ${env} ********"
-          echo "*************************************************"
-          terraform init || exit 1
-          cd ../../
-        done
-      fi 
+      for backend in tfbackend/*
+      do
+        env=${backend##*/}
+        env=${env%%.*}
+        echo ""
+        echo "*************** TERRAFORM INIT ******************"
+        echo "******* At environment: ${env} ********"
+        echo "*************************************************"
+        terraform init --backend-config=${backend} || exit 1
+      done
+# [END tf-init]
 
 # [START tf-plan]
 - id: 'tf plan'
@@ -54,36 +58,28 @@ steps:
   entrypoint: 'sh'
   args: 
   - '-c'
-  - | 
-      if [ -d "environments/$BRANCH_NAME/" ]; then
-        cd environments/$BRANCH_NAME
-        terraform plan
-      else
-        for dir in environments/*/
-        do 
-          cd ${dir}   
-          env=${dir%*/}
-          env=${env#*/}  
-          echo ""
-          echo "*************** TERRAFOM PLAN ******************"
-          echo "******* At environment: ${env} ********"
-          echo "*************************************************"
-          terraform plan || exit 1
-          cd ../../
-        done
-      fi 
+  - |
+      for vars in tfvars/*
+      do
+        env=${tfvars##*/}
+        env=${env%%.*}
+        echo ""
+        echo "*************** TERRAFORM PLAN ******************"
+        echo "******* At environment: ${env} ********"
+        echo "*************************************************"
+        terraform plan -var-file=${vars} || exit 1
+      done
 # [END tf-plan]
 
 # [START tf-apply]
 - id: 'tf apply'
   name: 'hashicorp/terraform:1.0.0'
   entrypoint: 'sh'
-  args: 
+  args:
   - '-c'
-  - | 
-      if [ -d "environments/$BRANCH_NAME/" ]; then
-        cd environments/$BRANCH_NAME      
-        terraform apply -auto-approve
+  - |
+      if [ -f "tfvars/$BRANCH_NAME.tfvars" ]; then
+        terraform apply -auto-approve -var-file="tfvars/${BRANCH_NAME}.tfvars"
       else
         echo "***************************** SKIPPING APPLYING *******************************"
         echo "Branch '$BRANCH_NAME' does not represent an official environment."
